# Generated by Django 4.2.1 on 2023-12-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_authorcategory_category_articlesandnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articlesandnews',
            options={'ordering': ['-time_create'], 'verbose_name': 'Статьи и новости', 'verbose_name_plural': 'Статьи и новости'},
        ),
        migrations.AlterModelOptions(
            name='authorcategory',
            options={'verbose_name': 'Категория автора', 'verbose_name_plural': 'Категории авторов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='showinfo',
            options={'verbose_name': 'Основная информация', 'verbose_name_plural': 'Основная информация'},
        ),
        migrations.AddField(
            model_name='articlesandnews',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='articlesandnews',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/info', verbose_name='Фото'),
        ),
        migrations.AddIndex(
            model_name='articlesandnews',
            index=models.Index(fields=['-time_create'], name='portal_arti_time_cr_3b3944_idx'),
        ),
    ]
