# Generated by Django 4.2.1 on 2023-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_uploadfiles_alter_articlesandnews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinfo',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file/%Y/%m/%d/', verbose_name='Файлы'),
        ),
    ]
