# Generated by Django 4.2.8 on 2023-12-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_categoryuser_user_cat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Группы студентов',
                'verbose_name_plural': 'Группа студентов',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group_stud',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.groupstudents', verbose_name='Группа студента'),
        ),
    ]
