# Generated by Django 4.2.8 on 2024-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_courses_options'),
        ('users', '0007_alter_user_date_birth_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudents',
            name='courses',
            field=models.ManyToManyField(default=None, null=True, related_name='courses', to='education.courses', verbose_name='Курсы'),
        ),
    ]
