# Generated by Django 4.2.8 on 2024-01-15 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_groupstudents_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudents',
            name='curator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator', to=settings.AUTH_USER_MODEL, verbose_name='Куратор группы'),
        ),
    ]
