# Generated by Django 4.2.8 on 2024-01-15 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_groupstudents_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudents',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники группы'),
        ),
    ]
