# Generated by Django 4.2.8 on 2024-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_curator',
            field=models.BooleanField(choices=[(False, 'Не куратор'), (True, 'Куратор')], default=0, verbose_name='Статус кураторства'),
        ),
    ]
