# Generated by Django 4.2.8 on 2024-01-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_courses_teacher'),
        ('users', '0013_user_is_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(default=None, null=True, related_name='course_teacher', to='education.courses', verbose_name='Курсы преподавателя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_stud',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.groupstudents', verbose_name='Группа пользователя'),
        ),
    ]
