# Generated by Django 4.2.8 on 2024-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_courses_teacher'),
        ('users', '0014_alter_user_courses_alter_user_group_stud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_teacher', to='education.courses', verbose_name='Курсы преподавателя'),
        ),
    ]
