# Generated by Django 4.2.8 on 2024-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('text', models.TextField(blank=True, verbose_name='Основная информация')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курс',
            },
        ),
    ]
